//LAN = LOCAL AREA NETWORK = REDE PRIVADA ENTRE OS DISPOSITIVOS DOMESTICOS

//CADA COMPUTADOR POSSUI UM IP UNICO PARA TODO O MUNDO/ OS IP VÃO DE 0 A 255

//IP= ENDERÇO DE UM COMPUTADOR EM UMA REDE.É COMO UM NUMERO DE TELEFONE

//PACOTE= UM BLOCO DE INFORMAÇÕES TROCADO ENTRE DOIS COMPUTADORES,COM ENDEREÇO IP DE ORIGEM E DESTINO.

//ROTEADOR=COMPUTADORES RESPONSAVEIS POR ENCAMINHA PACOTES EM UMA REDE PARA O DESTINATARIO CORRETO

//ROTA=O CAMINHO QUE UM PACOTE PRECISA TRILHAR PASSANDO POR DIVERSOS COMPUTADORES ATE CHEGAR MO SEU DESTINO

//HOP=UM SALTO QUE O PACOTE FAZ DURANTE O CAMINHO PASSANDO POR DOIS COMPUTADORES DIRETAMENTE CONECTADOS

//PEERING=ACORDO ENTRE DUAS EMPRESAS DE TELECOMICAÇÃO PARA ROTEAR TRAFEGO ENTRE ELAS

//SITE BOM PARA IPS 'IPINFO'